services:
  app:
    image: deminy/couchbase-benchmark
    platform: linux/amd64
    environment:
      # Value of environment variable LOG_LEVEL is one of the properties of the class Psr\Log\LogLevel.
      # Default value is "error" if not set.
      # @see https://github.com/php-fig/log/blob/3.0.2/src/LogLevel.php
      LOG_LEVEL: "error"
    links:
      - couchbase
    ports:
      - 80:80
    entrypoint: ["php", "./hyperf.php", "start"]
    volumes:
      - ./:/var/www
  couchbase:
    image: deminy/couchbase:7.2.2
    environment:
      CB_ADMIN: username
      CB_ADMIN_PASSWORD: password
      CB_BUCKET: test
    ports:
      - 8091
