services:
  app:
    image: deminy/couchbase-benchmark
    platform: linux/amd64
    environment:
      VERBOSE_LOGGING: "true"
    links:
      - couchbase
    ports:
      - 80:80
    entrypoint: ["php", "./hyperf.php", "start"]
    volumes:
      - ./:/var/www
  couchbase:
    image: deminy/couchbase:7.2.2
    environment:
      CB_ADMIN: username
      CB_ADMIN_PASSWORD: password
      CB_BUCKET: test
    ports:
      - 8091
