name: Syntax Checks

on: [ push, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Syntax Checks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Syntax Checks
        run: docker run --rm -v "$(pwd):/var/www" -w /var/www -i jakzal/phpqa:php8.2 php-cs-fixer fix --dry-run
