name: Syntax Checks

on: [ push, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Syntax Checks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Syntax Checks
        run: docker run -q --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php8.2-alpine php-cs-fixer fix -q --dry-run
